# Generated by Django 3.0.7 on 2020-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
