# Generated by Django 3.0.7 on 2020-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm', '0003_auto_20200713_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount_av_max',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='amount_av_min',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='price_max',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='price_min',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
    ]
