# Generated by Django 3.0.7 on 2020-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm', '0005_auto_20200713_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='option',
            field=models.CharField(choices=[('item1', 'item 1'), ('item2', 'item 2')], default='SOME STRING', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='price_min',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Veggies'), ('Nuts', 'Honey'), ('Tea', 'Legumes'), ('Oil', 'Wheat'), ('Flowers', 'Mushroom')], default='Fruits', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Istanbul', 'Izmir'), ('Denizli', 'Antalya'), ('Aydin', 'Rize')], default='Istanbul', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.CharField(choices=[('apple', 'banana'), ('orange', 'peach'), ('strawberry', 'kiwi'), ('coconut', 'avocado'), ('watermelon', 'cherry')], default='apple', max_length=15),
        ),
    ]
